# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Face(object):
    def setupUi(self, Face):
        Face.setObjectName("Face")
        Face.resize(1319, 689)
        self.centralwidget = QtWidgets.QWidget(Face)
        self.centralwidget.setObjectName("centralwidget")
        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(-30, -10, 1521, 761))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("E:\\Service Sales Robot\\Dataset\\face3.gif"))
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")
        Face.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Face)
        self.statusbar.setObjectName("statusbar")
        Face.setStatusBar(self.statusbar)

        self.retranslateUi(Face)
        QtCore.QMetaObject.connectSlotsByName(Face)

    def retranslateUi(self, Face):
        _translate = QtCore.QCoreApplication.translate
        Face.setWindowTitle(_translate("Face", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Face = QtWidgets.QMainWindow()
    ui = Ui_Face()
    ui.setupUi(Face)
    Face.show()
    sys.exit(app.exec_())
